language: go
matrix:
  allow_failures:
  - go: master
  include:
  - go: master
    env:
      - GOARCH=amd64
      - GOOS=linux
      - GO111MODULE=on
    cache:
      directories:
        - $HOME/.cache/go-build
        - $HOME/gopath/pkg/mod
  - go: 1.12.x
    env:
      - GOARCH=amd64
      - GOOS=linux
      - GO111MODULE=on
    cache:
      directories:
        - $HOME/.cache/go-build
        - $HOME/gopath/pkg/mod
  - go: 1.12.x
    env:
      - GOARCH=arm64
      - GOOS=linux
      - GO111MODULE=on
    cache:
      directories:
        - $HOME/.cache/go-build
        - $HOME/gopath/pkg/mod
  - go: 1.12.x
    env:
      - GOARCH=386
      - GOOS=linux
      - GO111MODULE=on
    cache:
      directories:
        - $HOME/.cache/go-build
        - $HOME/gopath/pkg/mod
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
