language: go
go:
  - 1.12
matrix:
  include:
  - env:
      - GOARCH=amd64
      - GOOS=linux
      - GO111MODULE=on
    cache:
      directories:
        - $HOME/.cache/go-build
        - $HOME/gopath/pkg/mod
  - env:
      - GOARCH=arm64
      - GOOS=linux
      - GO111MODULE=on
    cache:
      directories:
        - $HOME/.cache/go-build
        - $HOME/gopath/pkg/mod
  - env:
      - GOARCH=386
      - GOOS=linux
      - GO111MODULE=on
    cache:
      directories:
        - $HOME/.cache/go-build
        - $HOME/gopath/pkg/mod
notifications:
  email: false
