---

name: Git
on: [pull_request]
jobs:
  build:
    name: Branch is clean
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Fetch branches
        run: |
          git fetch --no-tags --prune --depth=1 origin "+refs/heads/${BASE}:refs/remotes/origin/${BASE}"
          git fetch --no-tags --prune --depth=1 origin "+refs/heads/${HEAD}:refs/remotes/origin/${HEAD}"
        env:
          BASE: ${{ github.base_ref }}
          HEAD: ${{ github.head_ref }}

      - name: Check no WIP of fixup commit
        env:
          BASE: origin/${{ github.base_ref }}
          HEAD: origin/${{ github.head_ref }}
        run: |
          export UNCLEAN_COMMITS="$(git log --oneline --grep '(fixup|wip)' -E -i "${BASE}..${HEAD}")"

          if [[ -n ${UNCLEAN_COMMITS} ]]; then
            printf "%s\n\n" "${UNCLEAN_COMMITS}"
            printf "%b%s\n%b" '\033[0;31m' 'You have WIP of fixup commit, please cleanup!' '\033[0m'

            exit 1
          fi
